baseURL = 'https://blog.hashbangbash.com/'
languageCode = "en-us"
theme = "console"
title = "#!bash blog"
copyright = "Vincent Batts"

[Author]
  name = "Vincent Batts"

[outputs]
  home = ['html','rss']
  section = ['html','rss']

[permalinks]
  post = '/:year/:month/:title/'
  code = '/:filename/'

[params]
  title = '#!bash blog'
  description = 'a place for passing fancies'
  custom_css = ["css/override.css"]
  animateStyle = "animated zoomIn fast" 
  titleCutting = true
  mastodon = "https://fosstodon.org/@vbatts"

[[params.navlinks]]
  name = "$HOME"
  pre = "<i class='fa fa-download'></i>"
  url = "https://hashbangbash.com/"

[[params.navlinks]]
  name = "posts/"
  pre = "<i class='fa fa-download'></i>"
  url = "posts/"

[[params.navlinks]]
  name = "tags/"
  pre = "<i class='fa fa-download'></i>"
  url = "tags/"

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
            unsafe = true

