name = 'blog.hashbangbash.com'
baseURL = 'http://blog.hashbangbash.com'
theme = "hyde"
#theme = "dimension"

[permalinks]
  post = '/:year/:month/:title/'

[[menu.main]]
  name = "Home"
  pre = "<i class='fa fa-download'></i>"
  url = "https://hashbangbash.com/"
  weight = -300

[[menu.main]]
  name = "Git"
  pre = "<i class='fa fa-download'></i>"
  url = "https://github.com/vbatts/"
  weight = -200

[[menu.main]]
  name = "Twitter"
  pre = "<i class='fa fa-download'></i>"
  url = "https://twitter.com/vbatts/"
  weight = -100

[params]
  title = '#!bash
  blog'
  description = 'a place for passing fancies'
  #logo = "fa-diamond"
  #copyright = "hashbangbash.com"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

