baseURL = 'https://blog.hashbangbash.com/'
languageCode = "en-us"
theme = "console"
#theme = "hyde-hyde"
title = "#!bash blog"
copyright = "Vincent Batts"

[Author]
  name = "Vincent Batts"

[permalinks]
  post = '/:year/:month/:title/'
  code = '/:filename/'

[params]
  title = '#!bash blog'
  description = 'a place for passing fancies'
  custom_css = ["css/override.css"]

[[params.social]]
  name = 'github'
  url = 'https://github.com/vbatts'

[[params.social]]
  name = 'mastodon'
  url = 'https://fosstodon.org/@vbatts'

#disqus = 'vbatts'

[[menu.main]]
  name = "Article Tags"
  pre = "<i class='fa fa-download'></i>"
  url = "/tags"
  weight = -400

[[menu.main]]
  name = "Home"
  pre = "<i class='fa fa-download'></i>"
  url = "https://hashbangbash.com/"
  weight = -300

[[menu.main]]
  name = "about"
  pre = "<i class='fa fa-download'></i>"
  url = "https://github.com/vbatts/me"
  weight = -200

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
            unsafe = true

