baseURL = 'http://blog.hashbangbash.com/'
languageCode = "en-us"
theme = "hyde"
#theme = "dimension"
title = "#!bash blog"
copyright = "Vincent Batts"

[Author]
  name = "Vincent Batts"

[permalinks]
  post = '/:year/:month/:title/'
  code = '/:filename/'

[params]
  title = '#!bash
  blog'
  description = 'a place for passing fancies'
  twitter = 'https://twitter.com/vbatts'
  github = 'https://github.com/vbatts/'
  disqus = 'vbatts'

[[menu.main]]
  name = "Article Tags"
  pre = "<i class='fa fa-download'></i>"
  url = "/tags"
  weight = -400

[[menu.main]]
  name = "Home"
  pre = "<i class='fa fa-download'></i>"
  url = "https://hashbangbash.com/"
  weight = -300

[[menu.main]]
  name = "Git"
  pre = "<i class='fa fa-download'></i>"
  url = "https://github.com/vbatts/"
  weight = -200

[[menu.main]]
  name = "Twitter"
  pre = "<i class='fa fa-download'></i>"
  url = "https://twitter.com/vbatts/"
  weight = -100
